# Generated by Django 4.2.5 on 2023-10-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='bio',
            field=models.TextField(default='no bio', max_length=300),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
