# Generated by Django 4.2.5 on 2023-11-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0002_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='online_status',
            field=models.BooleanField(default=False),
        ),
    ]
