# Generated by Django 4.2.5 on 2023-10-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0002_profiles_bio_alter_profiles_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='avatar',
            field=models.ImageField(default='avatar.svg', upload_to=''),
        ),
    ]
