# Generated by Django 4.2.5 on 2023-11-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
