# Generated by Django 4.2.5 on 2023-11-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0002_alter_profiles_first_name_alter_profiles_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
