# Generated by Django 4.2.5 on 2023-10-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0002_post_like_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
