# Generated by Django 4.2.5 on 2023-11-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0003_profiles_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
