# Generated by Django 4.2.5 on 2023-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facebook_ver2', '0004_alter_chatmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='message',
            field=models.TextField(),
        ),
    ]
