# Generated by Django 4.2.5 on 2023-11-13 07:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("facebook_ver2", "0004_alter_post_image_block"),
        ("facebook_ver2", "0004_block"),
    ]

    operations = []
